# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_apes.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(867, 694)
        self.water = QtWidgets.QTextEdit(Dialog)
        self.water.setGeometry(QtCore.QRect(290, 140, 104, 31))
        self.water.setObjectName("water")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 140, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 210, 131, 21))
        self.label_2.setObjectName("label_2")
        self.lux = QtWidgets.QTextEdit(Dialog)
        self.lux.setGeometry(QtCore.QRect(290, 200, 104, 31))
        self.lux.setObjectName("lux")
        self.motion = QtWidgets.QTextEdit(Dialog)
        self.motion.setGeometry(QtCore.QRect(290, 260, 104, 31))
        self.motion.setObjectName("motion")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 260, 161, 31))
        self.label_3.setObjectName("label_3")
        self.up = QtWidgets.QPushButton(Dialog)
        self.up.setGeometry(QtCore.QRect(610, 390, 106, 30))
        self.up.setObjectName("up")
        self.down = QtWidgets.QPushButton(Dialog)
        self.down.setGeometry(QtCore.QRect(610, 610, 106, 30))
        self.down.setObjectName("down")
        self.right = QtWidgets.QPushButton(Dialog)
        self.right.setGeometry(QtCore.QRect(710, 500, 106, 30))
        self.right.setObjectName("right")
        self.left = QtWidgets.QPushButton(Dialog)
        self.left.setGeometry(QtCore.QRect(490, 500, 106, 30))
        self.left.setObjectName("left")
        self.Auto = QtWidgets.QPushButton(Dialog)
        self.Auto.setGeometry(QtCore.QRect(670, 150, 106, 30))
        self.Auto.setObjectName("Auto")
        self.Manual = QtWidgets.QPushButton(Dialog)
        self.Manual.setGeometry(QtCore.QRect(520, 150, 106, 30))
        self.Manual.setObjectName("Manual")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(270, 20, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(460, 70, 20, 581))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(490, 70, 211, 41))
        self.label_5.setObjectName("label_5")
        self.mode = QtWidgets.QTextEdit(Dialog)
        self.mode.setGeometry(QtCore.QRect(710, 80, 104, 31))
        self.mode.setObjectName("mode")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(230, 80, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.stop = QtWidgets.QPushButton(Dialog)
        self.stop.setGeometry(QtCore.QRect(600, 240, 106, 30))
        self.stop.setObjectName("stop")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(510, 300, 291, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(530, 330, 271, 21))
        self.label_7.setObjectName("label_7")
        self.deg_mode = QtWidgets.QTextEdit(Dialog)
        self.deg_mode.setGeometry(QtCore.QRect(290, 330, 104, 31))
        self.deg_mode.setObjectName("deg_mode")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 330, 171, 21))
        self.label_8.setObjectName("label_8")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(510, 190, 291, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(30, 390, 191, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 450, 221, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(30, 510, 151, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(20, 570, 221, 21))
        self.label_12.setObjectName("label_12")
        self.tiva = QtWidgets.QTextEdit(Dialog)
        self.tiva.setGeometry(QtCore.QRect(290, 390, 104, 31))
        self.tiva.setObjectName("tiva")
        self.ultra_sensor = QtWidgets.QTextEdit(Dialog)
        self.ultra_sensor.setGeometry(QtCore.QRect(290, 450, 104, 31))
        self.ultra_sensor.setObjectName("ultra_sensor")
        self.lux_sensor = QtWidgets.QTextEdit(Dialog)
        self.lux_sensor.setGeometry(QtCore.QRect(290, 510, 104, 31))
        self.lux_sensor.setObjectName("lux_sensor")
        self.water_sensor = QtWidgets.QTextEdit(Dialog)
        self.water_sensor.setGeometry(QtCore.QRect(290, 570, 104, 31))
        self.water_sensor.setObjectName("water_sensor")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(50, 630, 221, 21))
        self.label_13.setObjectName("label_13")
        self.valve = QtWidgets.QTextEdit(Dialog)
        self.valve.setGeometry(QtCore.QRect(290, 630, 104, 31))
        self.valve.setObjectName("valve")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(20, 300, 391, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Water level"))
        self.label_2.setText(_translate("Dialog", "Lightness level"))
        self.label_3.setText(_translate("Dialog", "Obstacle distance "))
        self.up.setText(_translate("Dialog", "Forward"))
        self.down.setText(_translate("Dialog", "Backward"))
        self.right.setText(_translate("Dialog", "right"))
        self.left.setText(_translate("Dialog", "left"))
        self.Auto.setText(_translate("Dialog", "Auto"))
        self.Manual.setText(_translate("Dialog", "Manual"))
        self.label_4.setText(_translate("Dialog", "Floor Cleaner - Makes life easier!"))
        self.label_5.setText(_translate("Dialog", "Application Mode chosen"))
        self.label_6.setText(_translate("Dialog", "Display"))
        self.stop.setText(_translate("Dialog", "Stop"))
        self.label_7.setText(_translate("Dialog", "Hand control on manual mode"))
        self.label_8.setText(_translate("Dialog", "Operational status"))
        self.label_9.setText(_translate("Dialog", "Remote Node  status"))
        self.label_10.setText(_translate("Dialog", "Ultrasonic sensor status"))
        self.label_11.setText(_translate("Dialog", "Lux sensor  status"))
        self.label_12.setText(_translate("Dialog", "Water level  sensor status"))
        self.label_13.setText(_translate("Dialog", "Valve position"))


