# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_apes.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(637, 430)
        self.water = QtWidgets.QTextEdit(Dialog)
        self.water.setGeometry(QtCore.QRect(170, 170, 104, 31))
        self.water.setObjectName("water")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 180, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 230, 131, 21))
        self.label_2.setObjectName("label_2")
        self.lux = QtWidgets.QTextEdit(Dialog)
        self.lux.setGeometry(QtCore.QRect(170, 220, 104, 31))
        self.lux.setObjectName("lux")
        self.motion = QtWidgets.QTextEdit(Dialog)
        self.motion.setGeometry(QtCore.QRect(170, 270, 104, 31))
        self.motion.setObjectName("motion")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 270, 161, 31))
        self.label_3.setObjectName("label_3")
        self.up = QtWidgets.QPushButton(Dialog)
        self.up.setGeometry(QtCore.QRect(420, 200, 106, 30))
        self.up.setObjectName("up")
        self.down = QtWidgets.QPushButton(Dialog)
        self.down.setGeometry(QtCore.QRect(420, 340, 106, 30))
        self.down.setObjectName("down")
        self.right = QtWidgets.QPushButton(Dialog)
        self.right.setGeometry(QtCore.QRect(520, 270, 106, 30))
        self.right.setObjectName("right")
        self.left = QtWidgets.QPushButton(Dialog)
        self.left.setGeometry(QtCore.QRect(330, 270, 106, 30))
        self.left.setObjectName("left")
        self.Auto = QtWidgets.QPushButton(Dialog)
        self.Auto.setGeometry(QtCore.QRect(520, 80, 106, 30))
        self.Auto.setObjectName("Auto")
        self.Manual = QtWidgets.QPushButton(Dialog)
        self.Manual.setGeometry(QtCore.QRect(350, 80, 106, 30))
        self.Manual.setObjectName("Manual")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(150, 40, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(300, 160, 20, 251))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 310, 131, 21))
        self.label_5.setObjectName("label_5")
        self.mode = QtWidgets.QTextEdit(Dialog)
        self.mode.setGeometry(QtCore.QRect(170, 310, 104, 31))
        self.mode.setObjectName("mode")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(110, 110, 101, 21))
        self.label_6.setObjectName("label_6")
        self.stop = QtWidgets.QPushButton(Dialog)
        self.stop.setGeometry(QtCore.QRect(420, 390, 106, 30))
        self.stop.setObjectName("stop")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(330, 150, 291, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(360, 170, 271, 21))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Water level"))
        self.label_2.setText(_translate("Dialog", "Lightness level"))
        self.label_3.setText(_translate("Dialog", "Obstacle distance "))
        self.up.setText(_translate("Dialog", "up"))
        self.down.setText(_translate("Dialog", "down"))
        self.right.setText(_translate("Dialog", "right"))
        self.left.setText(_translate("Dialog", "left"))
        self.Auto.setText(_translate("Dialog", "Auto"))
        self.Manual.setText(_translate("Dialog", "Manual"))
        self.label_4.setText(_translate("Dialog", "Floor Cleaner - Makes life easier!"))
        self.label_5.setText(_translate("Dialog", "Mode"))
        self.label_6.setText(_translate("Dialog", "Display"))
        self.stop.setText(_translate("Dialog", "Stop"))
        self.label_7.setText(_translate("Dialog", "Hand control on manual mode"))


